### ISSUE TITLE
What's 'gym.envs.magic_cube'?

### ISSUE THREAD

**Issue by Kajiyu** [RobinChiu/gym-Rubiks-Cube#1]
python examples/play.py            
Traceback (most recent call last):
  File "examples/play.py", line 6, in <module>
    env = gym.make("RubiksCube-v0")
  File "/Users/YumaKajihara/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/Users/YumaKajihara/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/Users/YumaKajihara/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/Users/YumaKajihara/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/Users/YumaKajihara/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/Users/YumaKajihara/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/YumaKajihara/research/ikeg/code/gym-Rubiks-Cube/gym_Rubiks_Cube/envs/__init__.py", line 1, in <module>
    from gym_Rubiks_Cube.envs.rubiks_cube_env import RubiksCubeEnv
  File "/Users/YumaKajihara/research/ikeg/code/gym-Rubiks-Cube/gym_Rubiks_Cube/envs/rubiks_cube_env.py", line 5, in <module>
    from gym.envs.magic_cube import cube
ImportError: No module named 'gym.envs.magic_cube'

**Comment by RobinChiu** [comment]
It's a bug. I have already fixed it. Please pull it again. 
https://github.com/RobinChiu/gym-Rubiks-Cube/commit/7c64b1579ae62e7692760842b2f16668922358a9
